### ISSUE TITLE
parser_navigate fails for subcommands with aliases

### ISSUE THREAD

**Issue by hstock** [ribozz/sphinx-argparse#108]
`parser_navigate` throws an exception when trying to navigate to a subcommand with an alias.

Example: A subcommand `install` with alias `i`

The `name` attribute of the child data will be `install (i)` instead of `install`. Accordingly the `parser_navigate` fails because it uses the `name` attribute for comparison against path elements.

I have a test case and patch ready for this issue.

**Comment by tsibley** [comment]
I just ran into this same issue. The fix in PR #109 was merged over a year ago, but there's been no release since. I'd really appreciate it if someone could make a release to PyPI.

**Comment by tsibley** [comment]
@dpryan79 @alex-rudakov Any chance of this bug fix getting released soon?
