### ISSUE TITLE
Named Arguments listing - two hrules when there are two underlines in argument name

### ISSUE THREAD

**Issue by keithbriggs** [ribozz/sphinx-argparse#144]
This looks like a bug: when there are two underlines in an argument name, then the generated html has a rule above and below the name.   Normally, there is only a rule above the name.  (Actually, ` -print_versions` has only one underline, but we still get the two rules.)
![Screenshot from 2022-10-04 16-33-59](https://user-images.githubusercontent.com/5146641/193863441-b3bbd63b-030c-43ea-991d-03752c20fab0.png)

**Comment by JOJ0** [comment]
There is an actively maintained version of sphinx-argparse: https://github.com/ashb/sphinx-argparse/releases/tag/0.3.2

**Comment by keithbriggs** [comment]
See https://github.com/ashb/sphinx-argparse/issues/20 .
