### ISSUE TITLE
Formatting similar to RawDescriptionHelpFormatter

### ISSUE THREAD

**Issue by snmishra** [ribozz/sphinx-argparse#19]
I want to include a multi-paragraph description for my program. With argparse, I can do that using formatter_class=RawDescriptionHelpFormatter. sphinx-argparse always uses the default formatter class, which removes all extra whitespace.

**Comment by ribozz** [comment]
Commit merged, so would close issue even as pull request refer this as "partial fix", if further fixing needed. Another ticket can be created describing what's still missing there.

**Comment by ribozz** [comment]
Fix is included to 0.1.14 version
