### ISSUE TITLE
Each command alias will have its own documentation

### ISSUE THREAD

**Issue by ideasman42** [ribozz/sphinx-argparse#21]
When a subcommand has an alias set, it will have its documentation written for the original command and for every alias.

This is very easy to redo, see the example using alias in Python docs. - If you add multiple, you can easily see the problem.
https://docs.python.org/3/library/argparse.html#sub-commands

**Comment by ribozz** [comment]
Commit merged, so close the issue, would be nice also if we would have some nice example in docs that illustrates this topic. Ex. here: http://sphinx-argparse.readthedocs.org/en/latest/sample.html#generated-sample-1-command-with-subcommands
