### ISSUE TITLE
%(default) not supported in help message

### ISSUE THREAD

**Issue by fallen** [ribozz/sphinx-argparse#27]
It seems sphinx-argparse does not support expanding the %(default) contained in help string of the add_argument().
sphinx-argparse will literaly print "%(default)" instead of replacing it with the default argument of the add_argument().

Please, see https://docs.python.org/3/library/argparse.html#help

Thanks!

**Comment by tgarc** [comment]
Yes this is also an issue for me as I always include the %(default) variable in help strings.

**Comment by dpryan79** [comment]
I've now implemented this in the `develop` branch. Please give it a try and let me know if it has trouble with any of your use cases.
