### ISSUE TITLE
"Undocumented" string for subparsers

### ISSUE THREAD

**Issue by jamesra** [ribozz/sphinx-argparse#29]
I have a set of parsers added to a subparser.  For some reason the "description" field of each subparser is being displayed below an "Undocumented" string. 

It appears this could be fixed by removing a line of code in ext.py, but I am concerned about side effects.

![subparser_description](https://cloud.githubusercontent.com/assets/4551553/7379738/cdf794c6-edab-11e4-809b-949764a95f38.png)

**Comment by dpryan79** [comment]
I've just implemented an apparent fix for this in the next release. I think your solution was on the right track, but I found it preferable to still print `Undocumented` in cases where absolutely nothing else would be printed (e.g., no help or description or list of options).
