### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by jonathf** [ribozz/sphinx-argparse#30]
Setup:
OS: Ubuntu 14.04
Sphinx: 1.3.1
Sphinxarg: 0.1.15
Python: 2.7.6

Tried install both using `sudo pip install sphinxarg` and `sudo python setup.py install`from source, but with same results.

`sphinxarg.ext` is added to `conf.py` as follows:

    extensions = ["sphinx.ext.autodoc", "sphinx.ext.napoleon", "sphinxarg.ext"]

When I add the module, I get the following error:

    $ make latexpdf
    sphinx-build -b latex -d build/doctrees   source build/latex
    Running Sphinx v1.3.1
    loading pickled environment... not yet created
    building [mo]: targets for 0 po files that are out of date
    building [latex]: all documents
    updating environment: 1 added, 0 changed, 0 removed
    reading sources... [100%] index                                                                   
    Exception occurred:
      File "build/bdist.linux-x86_64/egg/sphinxarg/ext.py", line 324, in run
        mod = __import__(module_name, globals(), locals(), [attr_name])
    TypeError: Item in ``from list'' not a string
    The full traceback has been saved in /tmp/sphinx-err-RPSW25.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
    make: *** [latexpdf] Error 1

Same output for various other targets.

Any suggestions as how to get your extension working?

**Comment by ribozz** [comment]
On this line (ext.py line 324 https://github.com/ribozz/sphinx-argparse/blob/master/sphinxarg/ext.py#L324) user's module import is happening. So, it's not a problem with sphinx-argparse module availability, rather some typo/misconfiguration in directive used in user's docs.

Can you show please how you use sphinx-argparse directive?

**Comment by jonathf** [comment]
Ah. That was where the problem were.

I used the directive

    .. argparse::
        :module: mconvert
        :func: create_parser
        :prog: mconvert

However, Mconvert is the main module. I fixed the problem by changing it to

    .. argparse::
        :module: mconvert.__init__
        :func: create_parser
        :prog: mconvert

**Comment by standage** [comment]
@jonathf I just had a similar problem. My python package `kevlar` has a `cli` subpackage with the parser declared in `kevlar/cli/__init__.py`. The code to invoke the parser is `kevlar.cli.parser()`, and using `:module: kevlar.cli` worked on Mac/Python3, but not on Linux/Python2. Not until I changed it to `:module: kevlar.cli.__init__` did it work.

In hindsight, this is pretty obvious, but it took a while to figure out. Perhaps some clarification in the docs could help avoid confusion with this in the future.
