### ISSUE TITLE
Default arguments with string values should have strings in the output documentation

### ISSUE THREAD

**Issue by kratsg** [ribozz/sphinx-argparse#36]
<img width="547" alt="screenshot 2016-01-08 11 04 06" src="https://cloud.githubusercontent.com/assets/761483/12202387/8c5b6640-b5f7-11e5-9fd9-423ced23524a.png">

```python
lsf = drivers_parser.add_parser('lsf', help='Flock your jobs to lsf', usage=baseUsageStr.format('lsf'), formatter_class=lambda prog: CustomFormatter(prog, max_help_position=30))
lsf.add_argument('--optLSFConf', metavar='', type=str, required=False, default='-q short')
lsf.add_argument('--optLSFNFilesPerJob', metavar='', type=int, required=False, default=1)
```

As you can see, it looks like it suggests people should write `--optLSFConf=-q short` instead of `--optLSFConf="-q short"`.

**Comment by dpryan79** [comment]
My preferred solution would be to only put the defaults in quotes in cases where it includes a space. Would that suffice to you or do you have any other thoughts there?

**Comment by dpryan79** [comment]
BTW, I have a branch (`feature/quote_help_strings_fix36`) that implements my suggestion. Please feel free to give it a try!

**Comment by kratsg** [comment]
@dpryan79 I think it should always include quotes.

**Comment by dpryan79** [comment]
Fine by me, that's what I'll implement then :)

**Comment by dpryan79** [comment]
This is now implemented as requested in the `develop` branch.
