### ISSUE TITLE
both 'help' and 'description' text are output; only help is @replaced

### ISSUE THREAD

**Issue by rjplevin** [ribozz/sphinx-argparse#37]
I'm documenting a program with sub-commands. I use both `help="short message"` and `description="Longer message..."` options to `add_parser()`, which produces a nice summary when using the `-h` flag on the main command, and longer messages when using `-h` on sub-commands.

I note these problems:
1. The generated documentation includes both of these strings, which is redundant. If the `description` is given, the `help` should probably not be displayed.
2. The `@replace` directive currently replaces only the `help` text; the `description` is still shown.
3. The `@after` directive places the given text after the `help` text, but before the `description` text.

Currently I see no way to display both the command-line help messages I want at run time and the documentation I want via sphinx-argparse. 

Thanks!

**Comment by dpryan79** [comment]
@rjplevin: Can you give an example for this? It'd be helpful for changing the implementation.

**Comment by dpryan79** [comment]
This is now fixed in `develop` and will be present in the next release, which I'd like to push out sometime in the next week if I can get control of the pypi repository.
