### ISSUE TITLE
Markdown -> RST Conversion

### ISSUE THREAD

**Issue by sils** [ribozz/sphinx-argparse#44]
We don't really wanna use rst for our main description, rather markdown which is optimized for plain text readability.

Would be nice to auto convert it to rst, see also http://api.coala.io/en/latest/Developers/coala_settings.html - maybe using pandoc or somethin'

**Comment by dpryan79** [comment]
This isn't really related to sphinx-argparse, it just requires a tweak to your `conf.py` and installing a package. This also happens to be supported on readthedocs. Instructions are [here](http://blog.readthedocs.com/adding-markdown-support/), which I'll make reference to in the sphinx-argparse documentation.

**Comment by dpryan79** [comment]
Ah, that's on a per-file basis. I'll see if I can something together to flag markdown to be sent through [recommonmark](https://github.com/rtfd/recommonmark) first.

**Comment by dpryan79** [comment]
This is now implemented in the `develop` branch and will be present in the next release.
