### ISSUE TITLE
Align options table properly

### ISSUE THREAD

**Issue by sils** [ribozz/sphinx-argparse#45]
The options table isn't very well readable :/ See http://api.coala.io/en/latest/Developers/coala_settings.html

**Comment by dpryan79** [comment]
This is a sphinx styling related issue. At least things like `--format` being line wrapped you can presumably be fixed in CSS. This package passes the arguments back to sphinx as you specify them, sphinx is what does the actual formatting.

**Comment by dpryan79** [comment]
BTW, I have a section about this now [in the documentation](http://sphinx-argparse.readthedocs.io/en/stable/misc.html#text-wrapping-in-argument-tables).
