### ISSUE TITLE
Make "Options" a heading

### ISSUE THREAD

**Issue by sils** [ribozz/sphinx-argparse#46]
See http://api.coala.io/en/latest/Developers/coala_settings.html would be nice to have "Options", "Positional Arguments" etc. headers so they're linkable and give the document some structure

**Comment by dpryan79** [comment]
FYI, I'm working on this now in the `features/implement46` branch. It's mostly functional at this point, feel free to give it a try. One of the current issues is that one can't always link to groups of arguments if their header is duplicated (e.g., in a sub-commands with partially overlapping argument groups).

**Comment by dpryan79** [comment]
This is now implemented in the `develop` branch and will be included in the next release.
