### ISSUE TITLE
Can't download 0.1.16 using pip.

### ISSUE THREAD

**Issue by fjhaveri** [ribozz/sphinx-argparse#48]
I want to use 0.1.16 version but pip cannot find that version. Is there specific reason why the version 0.1.16 was not updated on pip ?

**Comment by dpryan79** [comment]
@ribozz hasn't granted me access and the pypi folks take forever to make changes. I've requested to get access to the pypi account, but haven't had the request granted yet. You can still use pip, but the command would then be something like:

    pip install --user --upgrade git+https://github.com/ribozz/sphinx-argparse

**Comment by ribozz** [comment]
> @ribozz hasn't granted me access and the pypi 
Sorry for that :(
@dpryan79 what's your username on PyPI? I will add maintainer access to you.

**Comment by dpryan79** [comment]
@ribozz: dpryan

**Comment by dpryan79** [comment]
This is now on pypi.
