### ISSUE TITLE
Handling arguments with empty default

### ISSUE THREAD

**Issue by eezltn** [ribozz/sphinx-argparse#51]
Arguments (both required and optional) with empty string as default value are rendered like this:

| name= | Argument with empty default |
| ------------- | ------------- |

Equal sign without anything after is confusing, would be better the leave out `=` or to show python empty string, like `name=''`.
Adding a new directive `:showemptydefault:` would be nice, so that empty defaults are shown only if the directive is given.

**Comment by dpryan79** [comment]
In the `develop` branch the whole `name=''` thing is done away with, since I've found that users find this incredibly confusing. Instead, it's be more like:

| option | help message |
| ------- | ----------------------------------- |
| name | Argument with empty default.<br/> <br/>Default = "" |
