### ISSUE TITLE
Required named arguments shown as optional

### ISSUE THREAD

**Issue by lordmauve** [ribozz/sphinx-argparse#58]
Version: sphinx-argparse==0.1.17

In the generated output I see required named arguments, eg

    parser.add_argument('--foo', required=True)

being grouped under the heading "optional arguments". This is likely to be very confusing for my application's users. The usage text is correct (ie. omits square brackets).

**Comment by lordmauve** [comment]
Screenshot demonstrating this issue:

![sphinx-argparse-issue58](https://cloud.githubusercontent.com/assets/617224/23944728/c56d6208-096b-11e7-9672-cdd3b28b7983.PNG)

As you can see in the usage, `--packdir` is a required argument.

**Comment by dpryan79** [comment]
Could you install the develop branch and check if this is fixed there?

**Comment by lordmauve** [comment]
I believe this is related to [Python issue #9694](http://bugs.python.org/issue9694).

**Comment by lordmauve** [comment]
@dpryan79 I can't easily install from Github at work.

Besides I believe this code in the develop branch is the culprit:
https://github.com/ribozz/sphinx-argparse/blob/develop/sphinxarg/parser.py#L159

**Comment by lordmauve** [comment]
I suggest calling the default argument groups "Named Arguments" and "Positional Arguments" - at least, that's how I'm going to work around this for the time being.

**Comment by dpryan79** [comment]
Seems like a reasonable path forward, that's what I'll implement then for the next release.

**Comment by dpryan79** [comment]
This has now been changed for the 0.2.0 release, due out Friday.
