### ISSUE TITLE
Default arguments for string parameters get mutated

### ISSUE THREAD

**Issue by lordmauve** [ribozz/sphinx-argparse#59]
Version: sphinx-argparse==0.1.17

When I use sphinx-argparse in multiple places within my documentation, default values for string parameters seem to grow additional levels of quoting.

For example, several subcommands have a deployment-template parameter. In each place it shows as having a different number of quotes:

    --deployment-template="""{tag_namespace}-{tag_version}"""

then

    --deployment-template=""""{tag_namespace}-{tag_version}""""

I believe this is because sphinx-argparse mutates my (singleton) parser object, at https://github.com/ribozz/sphinx-argparse/blob/master/sphinxarg/parser.py#L114

**Comment by dpryan79** [comment]
This should now be fixed for the 0.2.0 release, which is due out Friday.
