### ISSUE TITLE
Add minimum requirment for Sphinx

### ISSUE THREAD

**Issue by jayvdb** [ribozz/sphinx-argparse#67]
It is helpful to track the minimum usable version of Sphinx, especially as this also dictates the minimum version of docutils is available indirectly due to the Sphinx version.  This extension uses Sphinx and docutils .

A bit of digging shows that this extension requires at least Sphinx 1.0+ , and docutils 0.5, but it might actually be higher.

`sphinx.util.nodes.nested_parse_with_titles` was added in https://github.com/sphinx-doc/sphinx/commit/c5d67b032 (version 1.0b1)

`sphinx.util.compat.Directive` here was added in https://github.com/sphinx-doc/sphinx/commit/f2f62501e (version 0.6.2)

And Sphinx 1.0b1 dropped support for docutils 0.4 in https://github.com/sphinx-doc/sphinx/commit/f2f62501e

fwiw, [Sphinx 1.0 required](https://github.com/sphinx-doc/sphinx/blob/690fc257e9a539a4c193ba8efe5587f7c102785c/setup.py#L47) on `['Pygments>=0.8', 'Jinja2>=2.2', 'docutils>=0.5']`

**Comment by dpryan79** [comment]
Good catch, I'll try 1.1.0 (as an arbitrary old release) and set that as the minimum if it works. That's probably sufficiently old that it doesn't make sense to even look further back.

**Comment by dpryan79** [comment]
A little bit of playing around suggests that 1.2.0 is the oldest release that can build reasonably complex projects without error. I'll set that as the minimal version, then. Unless you need it sooner, that won't be live until the next release (no particular ETA at the moment).

**Comment by jayvdb** [comment]
That all sounds good.  No release to do a release just for this IMO.  It is a fairly obscure type of problem, and most people experiencing a problem like this with dependencies will likely consult the setup.py/requirements.txt on master anyway, so a commit there will suffice.

**Comment by dpryan79** [comment]
This should now be documented in both the `master` and `develop` branches.
