### ISSUE TITLE
Document changes

### ISSUE THREAD

**Issue by tony** [ribozz/sphinx-argparse#68]
Loving the plugin, thank for it

It'd be nice to know what changes between versions (re: https://github.com/cihai/unihan-etl/pull/17 and https://github.com/emre/kaptan/pull/52)

**Comment by dpryan79** [comment]
It's part of [the README](https://github.com/ribozz/sphinx-argparse#changelog--contributors) and in the notes on the releases tab.

**Comment by tony** [comment]
Right in front then. 

Open to moving it to a CHANGES file and making available via RTD?

Other thing is setup.py could use some metadata for the github project too

**Comment by dpryan79** [comment]
Yes to all of those suggestions :)

**Comment by dpryan79** [comment]
The changelog is now on RTD and I've added some metadata to setup.py for pypi for whenever the next release comes out.
