### ISSUE TITLE
sub-commands causes duplicate label 

### ISSUE THREAD

**Issue by gaborbernat** [ribozz/sphinx-argparse#88]
```
/src/doc/cli.rst:2: WARNING: duplicate label named arguments, other instance in /src/doc/cli.rst
/src/doc/cli.rst:2: WARNING: duplicate label named arguments, other instance in /src/doc/cli.rst
```

**Comment by dpryan79** [comment]
Yes, that happens sometimes, the rendering is still correct in my experience. If you have a case where it isn't please let me know and we can reopen this.

**Comment by jkugler** [comment]
I think I need to re-open this. This did not show up until I enabled `sphinx.ext.autosectionlabel`. In our doc system, we have all warnings treated as errors, since we want to make sure our docs are rendering correctly (e.g. no docs left out of index, etc.) So, this warning generates an error which kills the doc production In my case:

```
/home/jkugler/repos/frb/devkit-python/docs/commands/cache_secrets.rst:2:duplicate label named arguments, other instance in /home/jkugler/repos/frb/devkit-python/docs/commands/aquasec.rst
```
The two files concerned:

cache_secrets.rst
```
cache_secrets
=============

.. argparse::
   :ref: devkit.commands.cache_secrets._create_arg_parse
   :prog: dk cache_secrets

```

aquasec
```
aquasec
=======

.. argparse::
   :ref: devkit.commands.aquasec._create_arg_parse
   :prog: dk aquasec
```

Do you want to re-open this, or should I create a new bug?

**Comment by jkugler** [comment]
Adding this to config `autosectionlabel_prefix_document = True` gets rid of the above error, but then I get this one:
```
/home/jkugler/repos/frb/devkit-python/docs/commands/deploypkg.rst:2:duplicate label commands/deploypkg:named arguments, other instance in /home/jkugler/repos/frb/devkit-python/docs/commands/deploypkg.rst
```

deploypkg.rst
```
deploypkg
=========

.. argparse::
   :ref: devkit.commands.deploypkg._create_arg_parse
   :prog: dk deploypkg
```

**Comment by gaborbernat** [comment]
> Yes, that happens sometimes, the rendering is still correct in my experience. If you have a case where it isn't please let me know and we can reopen this.

The URL links are gibberish though in this case. IMHO the rendering still passes, but usability is sub-par and as such should be addressed.
