### ISSUE TITLE
noepilog option spelled wrong in basic usage documentation

### ISSUE THREAD

**Issue by cfelder** [ribozz/sphinx-argparse#90]
In basic usage the ``noepilog`` option is spelled ``noepilogue`` which is wrong in respect to the corresponding code.

**Comment by dpryan79** [comment]
Indeed, I just made it `noepilog` in the documentation, since that's what the code uses. It should have always been `noepilogue`, though. I'll leave this open as a reminder to accept both `noepilog` and `noepilogue`.
